version: '3'

tasks:
  build:
    desc: Develop the app
    sources:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    generates:
      - serve
    deps: [ envdoc, openapi, map, format ]
    cmds:
      - go build -o serve ./cmd/serve/main.go

  run:
    desc: Run the app
    watch: true
    sources:
      - 'api/*.yaml'
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    deps: [build]
    cmds:
      - ./serve

  debug:
    desc: Debug the app
    deps: [ envdoc, openapi, map, format ]
    interactive: true
    cmds:
      - go run -modfile=tools/go.mod github.com/cespare/reflex -r '(\.go$|go\.mod|go\.sum)' --decoration=none -s -- go run -modfile=tools/go.mod github.com/go-delve/delve/cmd/dlv debug --listen=:2345 --headless --disable-aslr --api-version=2 --accept-multiclient "./cmd/serve/main.go"

  format:
    sources:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    generates:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    cmds:
      - go run -modfile=tools/go.mod mvdan.cc/gofumpt -l -w cmd internal

  map:
    desc: Generate mappers
    deps: [map-port, map-adapter]

  map-port:
    internal: true
    desc: Generate a mapper for the port
    sources:
      - internal/*/port/mapper/mapper.go
    generates:
      - internal/*/port/mapper/*.gen.go
    cmds:
      - go generate ./internal/*/port/mapper

  map-adapter:
    internal: true
    desc: Generate a mapper for the adapter

  openapi:
    sources:
      - api/*.yaml
      - internal/*/port/config/*.yaml
    generates:
      - internal/*/port/api/*.gen.go
    cmds:
      - go generate ./internal/*/port/http.go

  envdoc:
    sources:
      - internal/*/service/config.go
    generates:
      - env.md
    cmds:
      - go generate ./internal/*/service/config.go
