version: '3'

tasks:
  build:
    desc: Build the binary
    sources:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    generates:
      - 'serve'
    deps: [ envdoc, openapi, map, format ]
    cmds:
      - go build -o serve ./cmd/serve/main.go

  run:
    desc: Run the app
    watch: true
    sources:
      - 'api/*.yaml'
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    deps: [build]
    cmds:
      - ./serve

  debug:
    desc: Debug the app
    deps: [ envdoc, openapi, map, format ]
    interactive: true
    cmds:
      - go run -modfile=tools/go.mod github.com/cespare/reflex -r '(\.go$|go\.mod|go\.sum)' --decoration=none -s -- go run -modfile=tools/go.mod github.com/go-delve/delve/cmd/dlv debug --listen=:2345 --headless --disable-aslr --api-version=2 --accept-multiclient "./cmd/serve/main.go"

  format:
    desc: Format code
    sources:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    generates:
      - 'cmd/**/*.go'
      - 'internal/**/*.go'
    cmds:
      - go run -modfile=tools/go.mod mvdan.cc/gofumpt -l -w cmd internal

  map:
    desc: Generate mappers
    deps: [ map-api, map-postgres ]

  map-api:
    internal: true
    desc: Generate a mapper for the api
    sources:
      - internal/*/port/mapper/api/goverter.go
      - internal/*/port/mapper/api/constructor.go
    generates:
      - internal/*/port/mapper/api/api_to_domain.gen.go
      - internal/*/port/mapper/api/domain_to_api.gen.go
    cmds:
      - go generate ./internal/*/port/mapper/api/goverter.go

  map-postgres:
    internal: true
    desc: Generate a mapper for postgres
    sources:
      - internal/*/adapter/mapper/postgres/goverter.go
      - internal/*/adapter/mapper/postgres/constructor.go
    generates:
      - internal/*/adapter/mapper/postgres/postgres_to_domain.gen.go
      - internal/*/adapter/mapper/postgres/domain_to_postgres.gen.go
    cmds:
      - go generate ./internal/*/adapter/mapper/postgres/goverter.go

  openapi:
    desc: Generate chi code from openapi spec
    sources:
      - api/*.yaml
      - internal/*/port/config/*.yaml
    generates:
      - internal/*/port/api/*.gen.go
    cmds:
      - go generate ./internal/*/port/http.go

  envdoc:
    desc: Generate documentation for the environment variables
    sources:
      - internal/*/service/config.go
    generates:
      - env.md
    cmds:
      - go generate ./internal/*/service/config.go
