// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package api

import (
	domain "github.com/cromerc/projectBase/internal/v1/domain"
	api "github.com/cromerc/projectBase/internal/v1/port/api"
)

type toAPI struct{}

func (c *toAPI) User(source domain.User) api.User {
	var apiUser api.User
	pInt64 := source.ID()
	apiUser.ID = &pInt64
	apiUser.Name = source.Username()
	return apiUser
}
func (c *toAPI) Users(source []domain.User) []api.User {
	var apiUserList []api.User
	if source != nil {
		apiUserList = make([]api.User, len(source))
		for i := 0; i < len(source); i++ {
			apiUserList[i] = c.User(source[i])
		}
	}
	return apiUserList
}
