// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	Petstore_authScopes = "petstore_auth.Scopes"
)

// TODO defines model for TODO.
type TODO struct {
	Description string `json:"description"`
	ID          *int64 `json:"id,omitempty"`
	Name        string `json:"name"`
}

// TODOs defines model for TODOs.
type TODOs = []TODO

// User defines model for User.
type User struct {
	ID   *int64 `json:"id,omitempty"`
	Name string `json:"name"`
}

// CreateTODOJSONRequestBody defines body for CreateTODO for application/json ContentType.
type CreateTODOJSONRequestBody = TODO

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = User

// UpdateUserFormdataRequestBody defines body for UpdateUser for application/x-www-form-urlencoded ContentType.
type UpdateUserFormdataRequestBody = User
